name: 'core3-b2'
description: 'Generic CI bot'
author: 'core3'
inputs:
  commentText: # change this
    required: true
    description: 'text of the comment to act on'
runs:
  using: 'node12'
  main: 'dist/index.js'
