name: fake_measure
on:
  workflow_dispatch:
    inputs:
      action_name:
        description: "Action name"
        required: false
        default: "run_something"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action name ${{ github.event.inputs.action_name }}!"